package bean;
<<<<<<< HEAD
// Generated 15/09/2023 09:35:39 by Hibernate Tools 4.3.1
=======
// Generated 21/09/2023 15:45:34 by Hibernate Tools 4.3.1
>>>>>>> 69a4caa (provinha enviada)


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GasCompraProduto generated by hbm2java
 */
@Entity
@Table(name="gas_compra_produto"
    ,catalog="db_geovane_silva"
)
public class GasCompraProduto  implements java.io.Serializable {


<<<<<<< HEAD
     private int idcompraProduto;
=======
     private int gasIdcompraProduto;
>>>>>>> 69a4caa (provinha enviada)
     private GasCompra gasCompra;
     private GasProduto gasProduto;

    public GasCompraProduto() {
    }

<<<<<<< HEAD
    public GasCompraProduto(int idcompraProduto, GasCompra gasCompra, GasProduto gasProduto) {
       this.idcompraProduto = idcompraProduto;
=======
    public GasCompraProduto(int gasIdcompraProduto, GasCompra gasCompra, GasProduto gasProduto) {
       this.gasIdcompraProduto = gasIdcompraProduto;
>>>>>>> 69a4caa (provinha enviada)
       this.gasCompra = gasCompra;
       this.gasProduto = gasProduto;
    }
   
     @Id 

    
<<<<<<< HEAD
    @Column(name="idcompra_produto", unique=true, nullable=false)
    public int getIdcompraProduto() {
        return this.idcompraProduto;
    }
    
    public void setIdcompraProduto(int idcompraProduto) {
        this.idcompraProduto = idcompraProduto;
=======
    @Column(name="gas_idcompra_produto", unique=true, nullable=false)
    public int getGasIdcompraProduto() {
        return this.gasIdcompraProduto;
    }
    
    public void setGasIdcompraProduto(int gasIdcompraProduto) {
        this.gasIdcompraProduto = gasIdcompraProduto;
>>>>>>> 69a4caa (provinha enviada)
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_compra_id_produto", nullable=false)
    public GasCompra getGasCompra() {
        return this.gasCompra;
    }
    
    public void setGasCompra(GasCompra gasCompra) {
        this.gasCompra = gasCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_produto_id_compra", nullable=false)
    public GasProduto getGasProduto() {
        return this.gasProduto;
    }
    
    public void setGasProduto(GasProduto gasProduto) {
        this.gasProduto = gasProduto;
    }




}


