package bean;
// Generated 15/09/2023 09:35:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GasProduto generated by hbm2java
 */
@Entity
@Table(name="gas_produto"
    ,catalog="db_geovane_silva"
)
public class GasProduto  implements java.io.Serializable {


     private int gasIdproduto;
     private int gasFornecedor;
     private int gasTipo;
     private String gasValor;
     private String gasNome;

    public GasProduto() {
    }

	
    public GasProduto(int gasIdproduto, int gasFornecedor, int gasTipo) {
        this.gasIdproduto = gasIdproduto;
        this.gasFornecedor = gasFornecedor;
        this.gasTipo = gasTipo;
    }
    public GasProduto(int gasIdproduto, int gasFornecedor, int gasTipo, String gasValor, String gasNome) {
       this.gasIdproduto = gasIdproduto;
       this.gasFornecedor = gasFornecedor;
       this.gasTipo = gasTipo;
       this.gasValor = gasValor;
       this.gasNome = gasNome;
    }
   
     @Id 

    
    @Column(name="gas_idproduto", unique=true, nullable=false)
    public int getGasIdproduto() {
        return this.gasIdproduto;
    }
    
    public void setGasIdproduto(int gasIdproduto) {
        this.gasIdproduto = gasIdproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_fornecedor", nullable=false)
    public int getGasFornecedor() {
        return this.gasFornecedor;
    }
    
    public void setGasFornecedor(int gasFornecedor) {
        this.gasFornecedor = gasFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_tipoo", nullable=false)
    public int getGasTipo() {
        return this.gasTipo;
    }
    
    public void setGasTipo(int gasTipo) {
        this.gasTipo = gasTipo;
    }

    
    @Column(name="gas_valor", length=45)
    public String getGasValor() {
        return this.gasValor;
    }
    
    public void setGasValor(String gasValor) {
        this.gasValor = gasValor;
    }

    
    @Column(name="gas_nome", length=45)
    public String getGasNome() {
        return this.gasNome;
    }
    
    public void setGasNome(String gasNome) {
        this.gasNome = gasNome;
    }


}


