package bean;
// Generated 15/09/2023 09:35:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GasTipo generated by hbm2java
 */
@Entity
@Table(name="gas_tipo"
    ,catalog="db_geovane_silva"
)
public class GasTipo  implements java.io.Serializable {


     private int gasIdTipo;
     private String gasNome;
     private String gasDescricao;
     private String gasPrecoMedio;
     private String gasUnidadeDeMedida;
     private String gasPeso;

    public GasTipo() {
    }

	
    public GasTipo(int gasIdTipo) {
        this.gasIdTipo = gasIdTipo;
    }
    public GasTipo(int gasIdTipo, String gasNome, String gasDescricao, String gasPrecoMedio, String gasUnidadeDeMedida, String gasPeso) {
       this.gasIdTipo = gasIdTipo;
       this.gasNome = gasNome;
       this.gasDescricao = gasDescricao;
       this.gasPrecoMedio = gasPrecoMedio;
       this.gasUnidadeDeMedida = gasUnidadeDeMedida;
       this.gasPeso = gasPeso;
    }
   
     @Id 

    
    @Column(name="gas_id_tipo", unique=true, nullable=false)
    public int getGasIdTipo() {
        return this.gasIdTipo;
    }
    
    public void setGasIdTipo(int gasIdTipo) {
        this.gasIdTipo = gasIdTipo;
    }

    
    @Column(name="gas_nome", length=45)
    public String getGasNome() {
        return this.gasNome;
    }
    
    public void setGasNome(String gasNome) {
        this.gasNome = gasNome;
    }

    
    @Column(name="gas_descricao", length=45)
    public String getGasDescricao() {
        return this.gasDescricao;
    }
    
    public void setGasDescricao(String gasDescricao) {
        this.gasDescricao = gasDescricao;
    }

    
    @Column(name="gas_preco_medio", length=45)
    public String getGasPrecoMedio() {
        return this.gasPrecoMedio;
    }
    
    public void setGasPrecoMedio(String gasPrecoMedio) {
        this.gasPrecoMedio = gasPrecoMedio;
    }

    
    @Column(name="gas_unidade_de_medida", length=45)
    public String getGasUnidadeDeMedida() {
        return this.gasUnidadeDeMedida;
    }
    
    public void setGasUnidadeDeMedida(String gasUnidadeDeMedida) {
        this.gasUnidadeDeMedida = gasUnidadeDeMedida;
    }

    
    @Column(name="gas_peso", length=45)
    public String getGasPeso() {
        return this.gasPeso;
    }
    
    public void setGasPeso(String gasPeso) {
        this.gasPeso = gasPeso;
    }
 


}


