package bean;
// Generated 15/09/2023 09:35:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GasUsuarios generated by hbm2java
 */
@Entity
@Table(name="gas_usuarios"
    ,catalog="db_geovane_silva"
)
public class GasUsuarios  implements java.io.Serializable {


     private int gasIdusuarios;
     private String gasCpf;
     private String gasApelido;
     private String gasNome;
     private Date gasDataNasc;
     private String gasTelefone;

    public GasUsuarios() {
    }

	
    public GasUsuarios(int gasIdusuarios) {
        this.gasIdusuarios = gasIdusuarios;
    }
    public GasUsuarios(int gasIdusuarios, String gasCpf, String gasApelido, String gasNome, Date gasDataNasc, String gasTelefone) {
       this.gasIdusuarios = gasIdusuarios;
       this.gasCpf = gasCpf;
       this.gasApelido = gasApelido;
       this.gasNome = gasNome;
       this.gasDataNasc = gasDataNasc;
       this.gasTelefone = gasTelefone;
    }
   
     @Id 

    
    @Column(name="gas_idusuarios", unique=true, nullable=false)
    public int getGasIdusuarios() {
        return this.gasIdusuarios;
    }
    
    public void setGasIdusuarios(int gasIdusuarios) {
        this.gasIdusuarios = gasIdusuarios;
    }

    
    @Column(name="gas_cpf", length=11)
    public String getGasCpf() {
        return this.gasCpf;
    }
    
    public void setGasCpf(String gasCpf) {
        this.gasCpf = gasCpf;
    }

    
    @Column(name="gas_apelido", length=45)
    public String getGasApelido() {
        return this.gasApelido;
    }
    
    public void setGasApelido(String gasApelido) {
        this.gasApelido = gasApelido;
    }

    
    @Column(name="gas_nome", length=45)
    public String getGasNome() {
        return this.gasNome;
    }
    
    public void setGasNome(String gasNome) {
        this.gasNome = gasNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gas_dataNasc", length=10)
    public Date getGasDataNasc() {
        return this.gasDataNasc;
    }
    
    public void setGasDataNasc(Date gasDataNasc) {
        this.gasDataNasc = gasDataNasc;
    }

    
    @Column(name="gas_telefone", length=11)
    public String getGasTelefone() {
        return this.gasTelefone;
    }
    
    public void setGasTelefone(String gasTelefone) {
        this.gasTelefone = gasTelefone;
    }




}


